#
# Travis CI configuration file for HTMLDOC.
#

language: c

env:
  global:
    - secure: "uEWddevIc1y3JU61tpDKh5+M4P+0M4OdMIsl9wG9iEhtAbWgIOlS5usTcg8+Y0y3QaglJi6UpeTlIetWp9KqYdCsUs2N9EntziOQroaHD70qTSohT9Lc1laauOVHdedcn7BAO4saOoLrErgt/E/FJGbA7UUxl9gWcJjfZviwd2uZwaxEN/sjKqXc5PwrJzgupAgIF8C5KZw7y+/R3NwdsVNVN5W6zLynpU9KIsgz8O6KXsZ0gSrt1fULy8z3EaPD/Xamrzio9Fim6j7y0v19qZUedxdK9yl0wJXng2KSgX6G/6n1521eiO5GQT7hlsaqHgFTtJ40KLzw9ovQaNzOgUvwqTYzV6xXs5RrJSnOARja/NLdHQZLAmy1I0jkkclRsymCLcOBBQnGfwbL3/It5ZaZtQGJXqfrCqlEAq60mCjQ8wPm9gnCt4g/ZXdeIFnFtLJgxB+JQ2ahzN08m2TA25km7wr7HSU8GV1D2kHXFKeMjFX0lLqg4owMf5E1cd8g9oljjPmMrVs1BzTj+hanq13HeIiuBzAc8f4OmrqugBe+0HpfPER91dKZuaQY8JyacXnm1SxJvgacZdLvWoRkKJhS6UU2z+ZPGzzOhrbfWs6O/RmkETH7BYh3ezX100pEzVsGXE1x71zxwhJB/FgEWPDgLh+YkmeNVUuJ0ehtqsk="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script: ./configure --enable-debug && make

addons:
  apt:
    packages: [cppcheck, libgnutls28-dev]

  coverity_scan:
    project:
      name: "michaelrsweet/htmldoc"
      description: "HTML conversion utility"
    notification_email: michael.r.sweet@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: coverity_scan

notifications:
  email:
    recipients:
      - msweet@msweet.org
